#!/bin/bash
clear
echo -e ""
echo -e "  \033[1;36mCERTIFICADO SSL PARA SEU DOMINIO\033[1;37m"
echo -e ""
read -p "  CRIAR CERTIFICADO SSL [N/S]: " -e -i S ok
[[ $ok = @(n|N) ]] && exit
clear
echo -e ""
echo -e "  \033[1;36mINSTALANDO PACOTES NECESSARIOS\033[1;37m"
echo -e ""
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}

copyfile (){
cd /etc/nginx/confid.d && wget https://raw.githubusercontent.com/NT-GIT-HUB/SSL_CERTIFICATE/main/domain‑name.conf
sleep 1
crontab -r >/dev/null 2>&1
(
	crontab -l 2>/dev/null
	echo "0 12 * * * /usr/bin/certbot renew --quiet"
) | crontab -

}

inst_nginx () {
apt install nginx -y
}
inst_certbot () {
apt install certbot -y
}
inst_python3_certbot_nginx () {
apt install python3-certbot-nginx -y
}
inst_ufw () {
apt install ufw -y
}
inst_software-properties-common () {
apt install software-properties-common -y
add-apt-repository ppa:certbot/certbot
service nginx reload
ufw allow https
}

echo -e "INSTALANDO NGINX"
fun_bar 'inst_nginx'
echo -e "INSTALANDO CERTBOT"
fun_bar 'inst_certbot'
echo -e "INSTALANDO PYTHON3-CERTBOT-NGINX"
fun_bar 'inst_python3_certbot_nginx'
echo -e "INSTALANDO UFW"
fun_bar 'inst_ufw'
echo -e "INSTALANDO SOFTWARE-PROPERTIES-COMMON"
fun_bar 'inst_software-properties-common'

clear
echo -e ""
echo -e "  \033[1;36mCRIANDO CONFIGURAÇÃO\033[1;37m"
echo -e ""
fun_bar 'copyfile'
sleep 2
clear
echo -e ""
read -p "  DOMÍNIO: " -e -i www.google.com dm
sed -i 's/www.google.com/'$dm'/g' /etc/nginx/conf.d/domain‑name.conf
clear
certbot --nginx
